# Generated by Django 4.0.1 on 2022-03-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='std',
            field=models.IntegerField(null=True),
        ),
    ]
