# Generated by Django 4.0.1 on 2022-03-17 06:09

from django.db import migrations
import myapp.manager


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_std'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', myapp.manager.UserManager()),
            ],
        ),
    ]
