# Generated by Django 4.0.1 on 2022-03-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isStaff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
