# Generated by Django 4.0.1 on 2022-03-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuser_isstaff_alter_customuser_referal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='isStaff',
        ),
    ]
