# Generated by Django 4.0.1 on 2022-03-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_exam_mcq_mcqquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='Exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.exam'),
        ),
    ]
