# Generated by Django 4.0.1 on 2022-03-20 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_exam_qno_exam_total_questions_mcq_qno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='id',
        ),
        migrations.AlterField(
            model_name='mcq',
            name='qno',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=30)),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.exam')),
                ('qno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mcq')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
