# Generated by Django 4.0.1 on 2022-03-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_mcq_id_alter_mcq_qno_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjective',
            fields=[
                ('qno', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=50)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.exam')),
            ],
        ),
    ]
