# Generated by Django 3.2.12 on 2022-05-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_exam_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentEmail', models.EmailField(max_length=254, unique=True)),
                ('examId', models.IntegerField(null=True)),
                ('img', models.CharField(max_length=3000)),
            ],
        ),
    ]
