# Generated by Django 3.2.12 on 2022-05-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_studentlogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentLogs',
            new_name='StudentLog',
        ),
    ]
