# Generated by Django 3.2.12 on 2022-05-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_studentlogs_studentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlog',
            name='img',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='studentlog',
            name='studentEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
